config/routes.rb
Rails.application.routes.draw do
  resources :jobs, except: [:edit, :update, :destroy]

  root "home#index"
  devise_for :users

  namespace :admin do
    root "dashboard#index"
    resources :jobs
    resources :categories
  end

end

app/models/job.rb
class Job
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Taggable

  #Relationships
  belongs_to :category
  belongs_to :company # Ou contractor

  validates :name, presence: true

  #Database
  field :name,        type: String
  field :description, type: String
  field :apply,       type: String
  field :highlight,   type: Boolean, default: false
  # tags_separator ','
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::AdminController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to [:admin, @job], notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: [:admin, @job.errors], status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to [:admin, @job], notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: [:admin, @job.errors], status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_name, :job_description, :job_apply, :jobs_category)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_name, :job_description, :job_apply, :jobs_category,:company_logo)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for @job, html: {role:'form'} do |f|
  = f.error_notification

  .form-inputs
    %p.lead Job information
    %hr
    = f.input :job_name
    = f.association :jobs_category, label_method: :category_name , value_method: :id, prompt: "Choose a Category"
    = f.input :job_description,as: :text, input_html:{class: 'wysihtml5',rows:'10'}
    = f.input :job_apply, as: :text, input_html:{rows:'6'}
    = f.input :company_logo
  .form-actions
    = f.button :submit

:javascript
  $(document).ready(function(){

    $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5();
    });

  })

app/views/jobs/_sidebar.html.haml
%ul.list-group
  - JobsCategory.all.each do |cat|
    %li.list-group-item
      = link_to cat.category_name
      %span.badge= cat.jobs.count

app/views/jobs/index.html.haml
.page-header
  %h1 Listing jobs

.row
  .col-lg-9
    - @jobs.each do |job|
      .media
        -#= image_tag "http://placehold.it/200x120", class: 'img-thumbnail pull-left'
        = image_tag job.company_logo_url, class: 'img-thumbnail pull-left'
        .media-body
          %h3.media-heading= link_to job.job_name, job
          %p= truncate(job.job_description, length: 200) {link_to "See Details", job}
          = job.jobs_category
          = job.created_at
  .col-lg-3
    = render 'sidebar'

app/views/jobs/new.html.haml
.page-header
  %h1 New job

= render 'form'

= link_to 'Back', admin_jobs_path

app/views/jobs/show.html.haml
%p#notice= notice
.page-header
  %h1= @job.job_name
%p= @job.job_description
.well
  %p=@job.job_apply

= link_to 'Back', jobs_path