config/routes.rb
Rails.application.routes.draw do
  resources :jobs, except: [:edit, :update, :destroy]

  root "home#index"
  devise_for :users

  namespace :admin do
    root "dashboard#index"
    resources :jobs
    resources :categories
  end

end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps

  #Validations
  validates :name, presence: true, uniqueness: true

  #Relationships
  has_many :jobs

  #Database
  field :name, type: String
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /jobs_categories
  # GET /jobs_categories.json
  def index
    @categories = Category.all
  end

  # GET /jobs_categories/1
  # GET /jobs_categories/1.json
  def show
  end

  # GET /jobs_categories/new
  def new
    @category = Category.new
  end

  # GET /jobs_categories/1/edit
  def edit
  end

  # POST /jobs_categories
  # POST /jobs_categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:admin, @category], notice: 'Jobs category was successfully created.' }
        format.json { render action: 'show', status: :created, location: [:admin, @category] }
      else
        format.html { render action: 'new' }
        format.json { render json: [:admin, @category.errors], status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs_categories/1
  # PATCH/PUT /jobs_categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to [:admin, @category], notice: 'Jobs category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: [:admin, @category.errors], status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs_categories/1
  # DELETE /jobs_categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/admin/categories/_form.html.haml
= simple_form_for [:admin, @category] do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
  .form-actions
    = f.submit 'Save'

app/views/admin/categories/edit.html.haml
%h1= t('admin.categories.edit.title')

= render 'form'

= link_to t('actions.show'), [:admin,@category]
\|
= link_to t('actions.back'), admin_categories_path

app/views/admin/categories/index.html.haml
.page-header
  %h1= t('admin.categories.title')

%table.table.table-striped
  %tr
    %th= attribute_name_for Category, :name
    %th= attribute_name_for Category, :created_at
    %th= t('actions.title')

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.created_at
      %td
        .btn-group.btn-group-sm
          = link_to t('actions.show'), [:admin,category], class: 'btn btn-default'
          = link_to t('actions.edit'), edit_admin_category_path(category), class: 'btn btn-default'
          = link_to t('actions.destroy'), [:admin,category], :method => :delete, :data => { :confirm => t('actions.confirm_destroy') }, class: 'btn btn-default'

%br

= link_to t('admin.categories.new'), new_admin_category_path, class: 'btn btn-primary'

app/views/admin/categories/new.html.haml
%h1 New jobs_category

= render 'form'

= link_to 'Back', admin_categories_path

app/views/admin/categories/show.html.haml
%p#notice= notice

%h1= t('actions.show')

= show_attributes @category, :name, :created_at

= link_to t('actions.edit'), edit_admin_category_path(@category)
\|
= link_to t('actions.back'), admin_categories_path